/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Bo.MascotaBo;
import Entidad.Mascota;
import conexion.Conexion;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author vrb00
 */
public class Frm_Mascota extends javax.swing.JFrame {

    private int id_mascota;
    private int id_persona;
    private int id_especie;
    private DefaultTableModel tabla;
    private Mascota mac = new Mascota();
    private MascotaBo macBo = new MascotaBo();
    private String mensaje = "";

    /**
     * Creates new form Frm_Persona
     */
    public Frm_Mascota() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mostrarDatosTabla();
        mostrarPersonas();
        mostrarEspecies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre_mascota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_raza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_mascotas = new javax.swing.JTable();
        combo_persona = new javax.swing.JComboBox<>();
        combo_especie = new javax.swing.JComboBox<>();
        txt_peso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_genero = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        combo_esterilizado = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_dueno = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_especie = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(49, 66, 82));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mascotas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jLabel2)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel1.setText("Escoge el dueño");

        jLabel3.setText("Nombre mascota");

        jLabel4.setText("Escoge la especie");

        jLabel5.setText("Raza");

        jLabel6.setText("Edad");

        jLabel7.setText("Peso");

        btn_agregar.setBackground(new java.awt.Color(1, 186, 59));
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(49, 66, 82));
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("Editar");
        btn_editar.setToolTipText("Guardar cambios");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(0, 204, 204));
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        tabla_mascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dueno", "Mascota", "Especie", "Raza", "Edad", "Peso", "Genero", "Esterilizada"
            }
        ));
        jScrollPane1.setViewportView(tabla_mascotas);

        combo_persona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el dueño" }));

        combo_especie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoge la especie" }));

        jLabel8.setText("Genero");

        combo_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoge el Genero", "Femenino", "Masculino" }));

        jLabel9.setText("Esterilizada");

        combo_esterilizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoge el estado", "Si", "No" }));

        menu_dueno.setText("Agregar");
        menu_dueno.add(jSeparator1);

        jMenuItem1.setText("Dueño");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_dueno.add(jMenuItem1);
        menu_dueno.add(jSeparator2);

        menu_especie.setText("Especie");
        menu_especie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_especieActionPerformed(evt);
            }
        });
        menu_dueno.add(menu_especie);

        jMenuBar1.add(menu_dueno);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_agregar)
                .addGap(84, 84, 84)
                .addComponent(btn_editar)
                .addGap(92, 92, 92)
                .addComponent(btn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminar)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_edad)
                    .addComponent(combo_persona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_especie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_genero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_raza)
                            .addComponent(txt_peso)
                            .addComponent(combo_esterilizado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nombre_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txt_nombre_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txt_raza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(combo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(combo_esterilizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_editar)
                    .addComponent(btn_buscar)
                    .addComponent(btn_eliminar))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Frm_Persona vista_persona = new Frm_Persona();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_especieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_especieActionPerformed
        // TODO add your handling code here:
        Frm_Especie vista_especie = new Frm_Especie();
    }//GEN-LAST:event_menu_especieActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (verificaDatos()) {
            try {
                mac.setId_persona(getPersona());
                mac.setNombre_mascota(txt_nombre_mascota.getText());
                mac.setId_especie(getEspecie());
                mac.setRaza(txt_raza.getText());
                mac.setEdad(Integer.parseInt(txt_edad.getText()));
                mac.setPeso(Float.parseFloat(txt_peso.getText()));
                mac.setGenero(getGenero());
                mac.setEsterilizada(getEsterilizada());
                mensaje = macBo.agregarMascota(mac);
                JOptionPane.showMessageDialog(this, mensaje);
                limpiarCampos();
                mostrarDatosTabla();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, mensaje);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que llenar todos los campos");
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String nombre_m= txt_nombre_mascota.getText();
        if(nombre_m != ""){
            try {
            ArrayList<Mascota> mascotas = macBo.buscarNombreMascota(nombre_m);

            for (Mascota m : mascotas) {
                id_mascota=m.getId_mascota();
                id_persona=m.getId_persona();
                setIndexComboPersona(m.getId_persona());
                txt_nombre_mascota.setText(m.getNombre_mascota());
                id_especie=m.getId_especie();
                setIndexComboEspecie(m.getId_especie());
                txt_raza.setText(m.getRaza());
                txt_edad.setText(String.valueOf(m.getEdad()));
                txt_peso.setText(String.valueOf(m.getPeso()));
                setIndexComboGenero(m.getGenero());
                setIndexComboEsterilizada(m.getEsterilizada());
            }
        } catch (Exception sql) {
            JOptionPane.showMessageDialog(null, sql);
        }
        } else {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre de mascota a buscar.");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (verificaDatos()) {
            try {
                mac.setId_mascota(id_mascota);
                mac.setId_especie(getEspecie());
                mac.setId_persona(getPersona());
                mac.setNombre_mascota(txt_nombre_mascota.getText());
                mac.setId_especie(getEspecie());
                mac.setRaza(txt_raza.getText());
                mac.setEdad(Integer.parseInt(txt_edad.getText()));
                mac.setPeso(Float.parseFloat(txt_peso.getText()));
                mac.setGenero(getGenero());
                mac.setEsterilizada(getEsterilizada());
                
                mensaje = macBo.actualizarMascota(mac);
                JOptionPane.showMessageDialog(this, mensaje);
                limpiarCampos();
                mostrarDatosTabla();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, mensaje);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que llenar todos los campos");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        try {
            mensaje = macBo.eliminarMascota(id_mascota);
            JOptionPane.showMessageDialog(this, mensaje);
            limpiarCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, mensaje);
        }
        mostrarDatosTabla();
    }//GEN-LAST:event_btn_eliminarActionPerformed
    private void mostrarDatosTabla() {
        DefaultTableModel contenido = (DefaultTableModel) tabla_mascotas.getModel();

        contenido.setRowCount(0);

        try {
            Connection conn = Conexion.Conectar();

            //Vista
            String procedureCall = "Select * from datos_mascota";
            CallableStatement mstmt = conn.prepareCall(procedureCall);

            mstmt.execute();

            ResultSet resultSet = mstmt.getResultSet();
            if (resultSet != null) {
                while (resultSet.next()) {

                    String nombrePersona = resultSet.getString("NombrePersona");
                    String nombre_mascota = resultSet.getString("NombreMascota");
                    String nombre_especie = resultSet.getString("NombreEspecie");
                    String nombre_raza = resultSet.getString("Raza");
                    Integer edad = resultSet.getInt("Edad");
                    float peso = resultSet.getFloat("Peso");
                    String genero = resultSet.getString("Genero");
                    int este = resultSet.getInt("Esterilizada");
                    String esterilizada;

                    if (este == 1) {
                        esterilizada = "Si";
                    } else {
                        esterilizada = "No";
                    }

                    ((DefaultTableModel) tabla_mascotas.getModel()).addRow(new Object[]{nombrePersona, nombre_mascota,
                        nombre_especie, nombre_raza, edad, peso, genero, esterilizada
                    });
                }
            }

            if (resultSet != null) {
                resultSet.close();
            }
            mstmt.close();
            conn.close();

        } catch (Exception e) {
            System.out.println("Error al conectar: " + e);
        }
    }

    private void mostrarPersonas() {

        try {
            Connection conn = Conexion.Conectar();

            //Vista
            String procedureCall = "Select * from datos_persona_emp";
            CallableStatement mstmt = conn.prepareCall(procedureCall);

            mstmt.execute();

            ResultSet resultSet = mstmt.getResultSet();
            if (resultSet != null) {
                while (resultSet.next()) {

                    Integer idPersona = resultSet.getInt("IDPersona");
                    String persona = resultSet.getString("Nombre");

                    // Agregar los datos al Combo Box
                    combo_persona.addItem(idPersona + "- " + persona);
                }
            }

            if (resultSet != null) {
                resultSet.close();
            }
            mstmt.close();
            conn.close();

        } catch (Exception e) {
            System.out.println("Error al conectar: " + e);
        }
    }

    private void mostrarEspecies() {

        try {
            Connection conn = Conexion.Conectar();

            //Vista
            String procedureCall = "Select * from datos_especie";
            CallableStatement mstmt = conn.prepareCall(procedureCall);

            mstmt.execute();

            ResultSet resultSet = mstmt.getResultSet();
            if (resultSet != null) {
                while (resultSet.next()) {

                    Integer idespecie = resultSet.getInt("ID");
                    String nombreEspecie = resultSet.getString("NombreEspecie");

                    // Agregar los datos al Combo Box
                    combo_especie.addItem(idespecie + "- " + nombreEspecie);
                }
            }

            if (resultSet != null) {
                resultSet.close();
            }
            mstmt.close();
            conn.close();

        } catch (Exception e) {
            System.out.println("Error al conectar: " + e);
        }
    }

    private boolean verificaDatos() {
        boolean verificar = false, verificarD = true;
        String nombre_mascota = txt_nombre_mascota.getText();
        String raza = txt_raza.getText();

        int edad = 0; // Valor por defecto, podrías asignar otro valor si es adecuado
        float peso = 0.0f;

        try {
            edad = Integer.parseInt(txt_edad.getText()); // Convertir el valor del campo de texto a entero
        } catch (NumberFormatException e) {
            // En caso de que la conversión falle (entrada no válida), la variable 'edad' quedará en su valor por defecto (0)
        }

        try {
            peso = Float.parseFloat(txt_peso.getText());
        } catch (NumberFormatException e) {
        }

        if (edad == 0 && nombre_mascota.isEmpty() && raza.isEmpty() && peso == 0.0f) {
            verificarD = false;
        }

        boolean verificarR = combo_persona.getSelectedIndex() != 0;
        boolean verificarEspecie = combo_especie.getSelectedIndex() != 0;
        boolean verificarEsterilizado = combo_esterilizado.getSelectedIndex() != 0;
        boolean verificarGenero = combo_genero.getSelectedIndex() != 0;

        if (verificarD && verificarR && verificarEspecie && verificarEsterilizado && verificarGenero) {
            verificar = true;
        }

        return verificar;
    }

    private int getPersona() {
        String Ddueño = combo_persona.getSelectedItem().toString();
        int id;
        try {
            String p2 = Ddueño.substring(0, 2);
            id = Integer.parseInt(p2 + "");
        } catch (Exception e) {
            String p1 = Ddueño.substring(0, 1);
            id = Integer.parseInt(p1 + "");
        }
        return id;
    }

    private int getEspecie() {
        String Despecie = combo_especie.getSelectedItem().toString();
        int id;
        try {
            String especie = Despecie.substring(0, 2);
            id = Integer.parseInt(especie + "");
        } catch (Exception e) {
            String especie = Despecie.substring(0, 1);
            id = Integer.parseInt(especie + "");
        }
        return id;
    }

    private String getGenero() {
        return combo_genero.getSelectedItem().toString();
    }

    private int getEsterilizada() {
        String est = combo_esterilizado.getSelectedItem().toString();
        int estirilizada;
        if (est == "Si") {
            estirilizada = 1;
        } else {
            estirilizada = 0;
        }
        return estirilizada;
    }

    private void setIndexComboPersona(int persona) {
        for (int i = 1; i < combo_persona.getItemCount(); i++) {

            String item = combo_persona.getItemAt(i);
            char personac = item.charAt(0);
            int personaO = Integer.parseInt(personac + "");
            if (personaO == persona) {
                combo_persona.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setIndexComboEspecie(int especie) {
        for (int i = 1; i < combo_especie.getItemCount(); i++) {

            String item = combo_especie.getItemAt(i);
            char especiec = item.charAt(0);
            String especieStr = String.valueOf(especiec);
            if (especieStr.equals(especie)) {
                combo_especie.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setIndexComboGenero(String genero) {
        for (int i = 1; i < combo_genero.getItemCount(); i++) {
            String item = combo_genero.getItemAt(i);
            char generoc = item.charAt(0);
            String generoStr = String.valueOf(generoc);
            if (generoStr.equals(genero)) {
                combo_genero.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setIndexComboEsterilizada(int esterilizada) {
        if(esterilizada ==1){
            combo_esterilizado.setSelectedIndex(1);
        } else {
            combo_esterilizado.setSelectedIndex(2);
        }
    }

    private void limpiarCampos() {
        txt_edad.setText("");
        txt_nombre_mascota.setText("");
        txt_peso.setText("");
        txt_raza.setText("");
        try {
            combo_especie.setSelectedIndex(0);
            combo_esterilizado.setSelectedIndex(0);
            combo_genero.setSelectedIndex(0);
            combo_persona.setSelectedIndex(0);
        } catch (ArrayIndexOutOfBoundsException e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Mascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JComboBox<String> combo_especie;
    private javax.swing.JComboBox<String> combo_esterilizado;
    private javax.swing.JComboBox<String> combo_genero;
    private javax.swing.JComboBox<String> combo_persona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menu_dueno;
    private javax.swing.JMenuItem menu_especie;
    private javax.swing.JTable tabla_mascotas;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre_mascota;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_raza;
    // End of variables declaration//GEN-END:variables
}
