package GUI;

import Bo.CitaBo;
import Entidad.Cita;
import conexion.Conexion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Frm_Cita extends javax.swing.JFrame {

    private int id_cita;
    private int id_mascota;
    private int id_servicio;
    private DefaultTableModel tabla;
    private Cita cita = new Cita();
    private CitaBo citaBo = new CitaBo();
    private String mensaje = "";

    public Frm_Cita() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mostrarDatosTabla();
        mostrarPersonaComboBox();
        mostrarMascotaComboBox();
        //obtenerSeleccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_citas = new javax.swing.JTable();
        combo_servicio = new javax.swing.JComboBox<>();
        combo_mascota = new javax.swing.JComboBox<>();
        fecha = new com.toedter.calendar.JDateChooser();
        txt_hora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_buscar_mascota = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_persona = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_servicio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(49, 66, 82));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cita");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(322, 322, 322))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel1.setText("Fecha:");

        jLabel3.setText("Hora:");

        jLabel4.setText("Servicio");

        jLabel5.setText("Mascota:");

        btn_agregar.setBackground(new java.awt.Color(1, 186, 59));
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(49, 66, 82));
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("Editar");
        btn_editar.setToolTipText("Guardar cambios");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(0, 204, 204));
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar.setBackground(new java.awt.Color(255, 0, 0));
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        tabla_citas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Hora", "Servicio", "Mascota", "Dueño", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla_citas);

        combo_servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        combo_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_servicioActionPerformed(evt);
            }
        });

        combo_mascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));

        jLabel6.setText("Estado");

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Completada", "Activa", "Cancelada" }));

        jLabel7.setText("Buscar Mascota");

        jMenu1.setText("Agregar");

        menu_persona.setText("Empleado");
        menu_persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_personaActionPerformed(evt);
            }
        });
        jMenu1.add(menu_persona);
        jMenu1.add(jSeparator1);

        menu_servicio.setText("Mascota");
        menu_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_servicioActionPerformed(evt);
            }
        });
        jMenu1.add(menu_servicio);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_servicio, 0, 193, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscar_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btn_editar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addGap(76, 76, 76)
                .addComponent(btn_eliminar)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(combo_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_buscar_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_editar)
                    .addComponent(btn_buscar)
                    .addComponent(btn_eliminar))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_personaActionPerformed
        // TODO add your handling code here:
        Frm_Empleado vista_empleado = new Frm_Empleado();
    }//GEN-LAST:event_menu_personaActionPerformed

    private void menu_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_servicioActionPerformed
        // TODO add your handling code here:
        Frm_Mascota vista_mascota = new Frm_Mascota();
    }//GEN-LAST:event_menu_servicioActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (verificaDatos()) {
            try {
                cita.setFecha(getFecha());
                cita.setHora(txt_hora.getText());
                cita.setId_mascota(getId_mascota());
                cita.setId_servicio(getId_servicio());
                cita.setEstado(getEstado());

                mensaje = citaBo.agregarCita(cita);
                JOptionPane.showMessageDialog(this, mensaje);
                limpiarCampos();
                mostrarDatosTabla();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, mensaje);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que llenar todos los campos");
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void combo_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_servicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_servicioActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        if (verificaDatos()) {
            try {
                cita.setId_cita(id_cita);
                cita.setFecha(getFecha());
                cita.setHora(txt_hora.getText());
                cita.setId_mascota(getId_mascota());
                cita.setId_servicio(getId_servicio());
                cita.setEstado(getEstado());
                
                mensaje = citaBo.actualizarCita(cita);
                JOptionPane.showMessageDialog(this, mensaje);
                limpiarCampos();
                mostrarDatosTabla();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, mensaje);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tienes que llenar todos los campos");
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if (txt_buscar_mascota.getText() != "") {
            try {
                ArrayList<Cita> citas = citaBo.buscarCitaMascota(txt_buscar_mascota.getText());

                for (Cita c : citas) {
                    id_cita = c.getId_cita();
                    fecha.setDate(c.getFecha());
                    txt_hora.setText(c.getHora());
                    setIndexComboMascota(c.getId_mascota());
                    setIndexComboServicio(c.getId_servicio());
                    setIndexComboEstado(c.getEstado());
                }
            } catch (Exception sql) {
                JOptionPane.showMessageDialog(null, sql);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tienes ingresar el nombre de una mascota");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        try {
            mensaje = citaBo.eliminarCita(id_cita);
            JOptionPane.showMessageDialog(this, mensaje);
            limpiarCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, mensaje);
        }
        mostrarDatosTabla();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Cita().setVisible(true);
            }
        });
    }

    private void mostrarDatosTabla() {
        DefaultTableModel contenido = (DefaultTableModel) tabla_citas.getModel();

        contenido.setRowCount(0);

        try {
            Connection conn = Conexion.Conectar();

            //Vista
            String procedureCall = "Select * from datos_cita";
            CallableStatement stmt = conn.prepareCall(procedureCall);

            stmt.execute();

            ResultSet resultSet = stmt.getResultSet();
            if (resultSet != null) {
                while (resultSet.next()) {

                    Integer id = resultSet.getInt("ID");
                    String fecha = resultSet.getString("Fecha");
                    String hora = resultSet.getString("Hora");
                    String nombre_servicio = resultSet.getString("NombreServicio");
                    String nombre_mascota = resultSet.getString("NombreMascota");
                    String nombre_p = resultSet.getString("NombrePersona");
                    String estado = resultSet.getString("Estado");

                    ((DefaultTableModel) tabla_citas.getModel()).addRow(new Object[]{id, fecha, hora,
                        nombre_servicio, nombre_mascota, nombre_p, estado
                    });
                }
            }

            if (resultSet != null) {
                resultSet.close();
            }
            stmt.close();
            conn.close();

        } catch (Exception e) {
            System.out.println("Error al conectar: " + e);
        }
    }

    private boolean verificaDatos() {
        boolean verificar = false, verificarD = false;
        String hora = txt_hora.getText();
        String fecha_cita = "";

        try {
            Date selectedDate = fecha.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            fecha_cita = dateFormat.format(selectedDate);
        } catch (Exception e) {
        }

        if (fecha_cita != "" && hora != "") {
            verificarD = true;
        }

        boolean verificarR = false;
        if (combo_servicio.getSelectedIndex() != 0) {
            if (combo_mascota.getSelectedIndex() != 0) {
                if (combo_estado.getSelectedIndex() != 0) {
                    verificarR = true;
                }
            }
        }

        if (verificarD && verificarR) {
            verificar = true;
        }
        return verificar;
    }

    private String getEstado() {
        return combo_estado.getSelectedItem().toString();
    }

    private int getId_mascota() {
        String Dpersona = combo_mascota.getSelectedItem().toString();
        int id;
        try {
            String persona = Dpersona.substring(0, 2);
            id = Integer.parseInt(persona + "");
        } catch (Exception e) {
            String persona = Dpersona.substring(0, 1);
            id = Integer.parseInt(persona + "");
        }
        return id;
    }

    private int getId_servicio() {
        String Dpersona = combo_servicio.getSelectedItem().toString();
        int id;
        try {
            String persona = Dpersona.substring(0, 2);
            id = Integer.parseInt(persona + "");
        } catch (Exception e) {
            String persona = Dpersona.substring(0, 1);
            id = Integer.parseInt(persona + "");
        }
        return id;
    }

    private Date getFecha() {
        Date selectedDate = null;
        try {
            selectedDate = fecha.getDate();

        } catch (Exception e) {
        }
        return selectedDate;
    }

    private void setIndexComboMascota(int id_m) {
        for (int i = 1; i < combo_mascota.getItemCount(); i++) {

            String item = combo_mascota.getItemAt(i);
            char personac = item.charAt(0);
            int persona = Integer.parseInt(personac + "");
            if (persona == id_m) {
                combo_mascota.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setIndexComboServicio(int id_s) {
        for (int i = 1; i < combo_servicio.getItemCount(); i++) {

            String item = combo_servicio.getItemAt(i);
            char personac = item.charAt(0);
            int persona = Integer.parseInt(personac + "");
            if (persona == id_s) {
                combo_servicio.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setIndexComboEstado(String estado) {
        for (int i = 0; i < combo_estado.getItemCount(); i++) {
            String item = (String) combo_estado.getItemAt(i); // Cambio aquí
            if (item.equals(estado)) {
                combo_estado.setSelectedIndex(i);
                break;
            }
        }

    }

    private void mostrarPersonaComboBox() {

        try {
            Connection conn = Conexion.Conectar();

            //Vista
            String procedureCall = "Select * from datos_servicio";
            CallableStatement stmt = conn.prepareCall(procedureCall);

            stmt.execute();

            ResultSet resultSet = stmt.getResultSet();
            if (resultSet != null) {
                while (resultSet.next()) {

                    Integer serID = resultSet.getInt("ID");
                    String nombre_ser = resultSet.getString("NombreServicio");

                    combo_servicio.addItem(serID + "- " + nombre_ser);
                }
            }

            if (resultSet != null) {
                resultSet.close();
            }
            stmt.close();
            conn.close();

        } catch (Exception e) {
            System.out.println("Error al conectar: " + e);
        }
    }

    private void mostrarMascotaComboBox() {
        try {
            Connection conn = Conexion.Conectar();

            //Vista
            String procedureCall = "Select * from DATOS_MASCOTA_CITA";
            CallableStatement stmt = conn.prepareCall(procedureCall);

            stmt.execute();

            ResultSet resultSet = stmt.getResultSet();
            if (resultSet != null) {
                while (resultSet.next()) {

                    Integer mascotaId = resultSet.getInt("IDMascota");
                    String nombreMas = resultSet.getString("NombreMascota");

                    combo_mascota.addItem(mascotaId + "- " + nombreMas);
                }
            }

            if (resultSet != null) {
                resultSet.close();
            }
            stmt.close();
            conn.close();

        } catch (Exception e) {
            System.out.println("Error al conectar: " + e);
        }
    }

    private void limpiarCampos() {
        fecha.setSelectableDateRange(null, null);
        fecha.setDate(null);

        txt_hora.setText("");
        try {
            combo_mascota.setSelectedIndex(0);
            combo_servicio.setSelectedIndex(0);
        } catch (ArrayIndexOutOfBoundsException e) {
        }
    }

    /*
    private int getId_persona() {
        String Dpersona = combo_empleado.getSelectedItem().toString();
        int id;
        try {
            String persona = Dpersona.substring(0, 2);
            id = Integer.parseInt(persona + "");
        } catch (Exception e) {
            String persona = Dpersona.substring(0, 1);
            id = Integer.parseInt(persona + "");
        }
        return id;
    }

    private int getInt_Mascota() {
        String Dcliente = combo_mascota.getSelectedItem().toString();
        int Mascota;
        try {
            String masc = Dcliente.substring(0, 2);
            Mascota = Integer.parseInt(masc + "");
        } catch (Exception e) {
            String masc = Dcliente.substring(0, 1);
            Mascota = Integer.parseInt(masc + "");
        }
        return Mascota;
    }

    private void setIndexComboCliente(int cliente) {
        for (int i = 1; i < combo_empleado.getItemCount(); i++) {

            String item = combo_empleado.getItemAt(i);
            char clien = item.charAt(0);
            int persona = Integer.parseInt(clien + "");
            if (persona == cliente) {
                combo_empleado.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setIndexComboProducto(int producto) {
        for (int i = 1; i < combo_mascota.getItemCount(); i++) {

            String item = combo_mascota.getItemAt(i);
            char masco = item.charAt(0);
            int masc = Integer.parseInt(masco + "");
            if (masc == producto) {
                combo_mascota.setSelectedIndex(i);
                break;
            }
        }
    }
}
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JComboBox<String> combo_mascota;
    private javax.swing.JComboBox<String> combo_servicio;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menu_persona;
    private javax.swing.JMenuItem menu_servicio;
    private javax.swing.JTable tabla_citas;
    private javax.swing.JTextField txt_buscar_mascota;
    private javax.swing.JTextField txt_hora;
    // End of variables declaration//GEN-END:variables
}
